[tool.poetry]
name = "trdy"
version = "0.1.0"
description = "A Streamlit app"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4"
streamlit = "^1.27.0"
pandas = "^2.1.0"
numpy = "^1.26.0"
tld = ">=0.13,<4"
trafilatura = "^2.0.0"
courlan = ">=1.3.2"
pymupdf = ">=1.25.3,<2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
