[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.7, <4"

dependencies = [
    "openai>=1.63.2",
    "pdfminer-six>=20240706",
    "pdfminer>=20191125",
    "streamlit>=1.42.2",
    "trafilatura>=2.0.0",
    "anthropic>=0.46.0",
    "pymupdf>=1.25.3",
    "fitz>=0.0.1.dev2",
]
