[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Streamlit Legal Document Analyzer"
requires-python = ">=3.10.0"
dependencies = [
    "streamlit>=1.42.2",
    "openai>=1.63.2",
    "pdfminer-six>=20240706",
    "trafilatura>=2.0.0",
    "anthropic>=0.46.0",
    "pymupdf>=1.25.3",
    "requests>=2.32.3"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
